default:
    method: "hlt_stoch"
    max_steps: 200
    max_frames: 10000
    frame_skip: 2
    model_lr: !!float 3e-4
    policy_lr: !!float 3e-4
    value_lr: !!float 3e-4
    soft_q_lr: !!float 3e-4
    reward_scale: 1.0
    horizon: 5
    model_iter: 5
    trajectory_samples: 60
    lam: 0.1

PendulumEnv:
    max_frames: 10000
    frame_skip: 4
    max_steps: 200
    lam: 0.1
    model_iter: 5

InvertedPendulumBulletEnv:
    max_frames: 10000
    frame_skip: 4
    max_steps: 500
    lam: 0.1
    model_iter: 5

HopperBulletEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 4
    horizon: 10

HalfCheetahBulletEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 5
    lam: 0.1
    horizon: 10
