default:
    method: "hlt_deter"
    max_steps: 200
    max_frames: 10000
    frame_skip: 2
    model_lr: !!float 3e-4
    policy_lr: !!float 3e-4
    value_lr: !!float 3e-4
    soft_q_lr: !!float 3e-4
    planner_lr: 0.1
    reward_scale: 1.0
    horizon: 5
    model_iter: 5
    trajectory_samples: 60
    lam: 0.1

InvertedPendulumBulletEnv:
    max_frames: 10000
    frame_skip: 4
    max_steps: 1000
    model_iter: 5

HopperBulletEnv:
    max_frames: 80000
    max_steps: 2000
    frame_skip: 4
    horizon: 10
    planner_lr: 0.001

HalfCheetahBulletEnv:
    max_frames: 80000
    max_steps: 2000
    frame_skip: 5
    horizon: 10
