default:
    method: "hlt_stoch"
    max_steps: 200
    max_frames: 10000
    frame_skip: 2
    model_lr: !!float 3e-3
    policy_lr: !!float 3e-3
    value_lr: !!float 3e-4
    soft_q_lr: !!float 3e-4
    reward_scale: 1.0
    horizon: 5
    model_iter: 5
    trajectory_samples: 20
    lam: 0.1
    activation_fun: 'ReLU'

PendulumEnv:
    activation_fun: 'sin'
    max_frames: 10000
    frame_skip: 4
    max_steps: 200
    # lam: 0.1
    # model_iter: 5

InvertedPendulumBulletEnv:
    activation_fun: 'sin'
    max_frames: 10000
    frame_skip: 4
    max_steps: 200
    lam: 0.1
    model_iter: 5

InvertedPendulumEnv_sin:
    activation_fun: 'sin'
    max_frames: 50000
    frame_skip: 4
    max_steps: 1000
    horizon: 10
    # lam: 0.1
    # model_iter: 5
    
InvertedPendulumEnv:
#     activation_fun: 'sin'
    max_frames: 50000
    frame_skip: 4
    max_steps: 1000
    horizon: 10
    # lam: 0.1
    # model_iter: 5

# HopperBulletEnv:
#     max_frames: 50000
#     max_steps: 1000
#     frame_skip: 4
#     horizon: 10

# HopperBulletEnv:
#     max_frames: 50000
#     max_steps: 1000
#     frame_skip: 1
#     lam: 0.1


HopperEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 4
    lam: 0.2
#     horizon: 10

# HalfCheetahBulletEnv:
#     max_frames: 50000
#     max_steps: 1000
#     frame_skip: 5
#     lam: 0.5
#     horizon: 10

HalfCheetahEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 1
    lam: 0.2
    horizon: 10

# ReacherBulletEnv:
#     max_frames: 10000
#     max_steps: 100
#     frame_skip: 1
#     lam: 0.01
#     horizon: 10
