default:
    method: "mpc_deter"
    max_steps: 200
    max_frames: 10000
    frame_skip: 2
    model_lr: !!float 3e-4
    reward_scale: 1.0
    horizon: 5
    model_iter: 5
    activation_fun: 'ReLU'

PendulumEnv:
    activation_fun: 'sin'
    max_frames: 10000
    frame_skip: 4
    max_steps: 200
    model_iter: 5

InvertedPendulumBulletEnv:
    activation_fun: 'sin'
    max_frames: 10000
    frame_skip: 4
    max_steps: 200
    model_iter: 5

HopperBulletEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 4
    horizon: 5

HalfCheetahBulletEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 5
    horizon: 10
