default:
    max_steps: 200
    max_frames: 10000
    frame_skip: 2
    model_lr: !!float 3e-4
    policy_lr: !!float 3e-4
    value_lr: !!float 3e-4
    soft_q_lr: !!float 3e-4
    reward_scale: 1.0

InvertedPendulumBulletEnv:
    max_frames: 10000
    frame_skip: 4
    max_steps: 500

# HopperBulletEnv:
#     max_frames: 50000
#     max_steps: 1000
#     frame_skip: 4

HopperBulletEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 1

# HalfCheetahBulletEnv:
#     max_frames: 50000
#     max_steps: 1000
#     frame_skip: 5
HalfCheetahBulletEnv:
    max_frames: 50000
    max_steps: 1000
    frame_skip: 1
